### PR TITLE
Path to retroarch not needed for RetroPlayer.

### PR DESCRIPTION
**Pull request by MrTarantula**
This should fix the problem in #32. I haven't tested it but it's a very small change.

### CODE REVIEW

**Comment by zach-morris** [comment]
Thanks!  I'll add this (and test it).

**Comment by MrTarantula** [comment]
I've tested it, and it works, but I don't like how I have to set RetroPlayer, hit OK, then open settings again. I'm not really a python or Kodi addon dev, but is there not a way to have the setting available as soon as it's set? If you can give me an example of how that would work, I could spend some time refactoring (as its own PR).

In the meantime I'll look into python and addon development.

**Comment by zach-morris** [comment]
I've contemplated that issue.  The only option I see is to have the addon (or wizard) see that a setting is not set, then directly prompt the user for the value and set the settings.xml value to what they input.  Kind of a pain coding wise, but doable.

**Comment by zach-morris** [comment]
Merged.

**Pull request closed without merging**
